Refactoring: refactoring and move resource file absLvl.
QuasarApp/Crawl pull request #73
Opened 2021-07-04 15:14 UTC by IgorekLoschinin

fix #72 Refactoring abstract level.

2021-07-04 15:15 UTC, EndrII commented
Fix windows build before my review

2021-07-04 15:54 UTC, EndrII requested changes

2021-07-04 15:54 UTC, EndrII commented on src/Client/CMakeLists.txt
> +target_link_libraries(${CURRENT_PROJECT} PUBLIC ${PROJECT_NAME}Core AbstractLvl)
```suggestion
target_link_libraries(${CURRENT_PROJECT} PUBLIC ${PROJECT_NAME}Core TestLvl AbstractLvl)
```

use on line for include libraries

2021-07-04 15:54 UTC, EndrII commented on src/CrawlAbstractLvl/CMakeLists.txt
> +add_definitions(-DSnakeProject_LIBRARY)
you must change the default library define to CRAWL_ABSTRACT_LEVEL_LIBRARY define
and do not forget change in in your global.h file

2021-07-04 15:54 UTC, EndrII commented on src/CrawlAbstractLvl/private/abslvlcontrol.h
> + * @brief The TestControl class This controll support custom camera-ratation functions.
The description of the class douse not correspond of reality.

2021-07-04 15:54 UTC, EndrII commented on src/CrawlAbstractLvl/private/abslvlcontrol.h
> +#ifndef TESTCONTROL_H
you use duplicate macros with the test lvl library.

2021-07-04 15:54 UTC, EndrII commented on src/CrawlAbstractLvl/private/abslvlworld.cpp
> +    return new Snake();
you should create a own Snake class item. For more information see the test lvl.

2021-07-04 15:54 UTC, EndrII commented on src/CrawlAbstractLvl/private/abslvlworld.h
> +#ifndef WORLD_H
please change this define name to the name of the class .
example : 
ABSLEVELWORLD_H

2021-07-04 15:54 UTC, EndrII commented on src/CrawlAbstractLvl/private/obstaclered.cpp
> +    setSize({10,10,10});
the 10 size it is very gib size. So use the 1 size.

2021-07-04 15:54 UTC, EndrII commented on src/CrawlAbstractLvl/private/snake.h
> +class Snake : public IPlayer {
The snake object must be  inherit of the Snake class in core module.

2021-07-04 15:54 UTC, EndrII commented on src/CrawlAbstractLvl/private/snake.h
> +#ifndef SNAKE_H
This class will be conflict with Snake class of the core module. so please rename your snake class.

2021-07-05 20:32 UTC, EndrII commented
@Oleg-designer  please build this branch and make manual tests of this level. 
After test add new issues  and attach them to this pull request.

2021-07-05 20:33 UTC, EndrII commented
@IgorekLoschinin This look good for me but i think that this level still not works correctly.

2021-07-06 08:15 UTC, Oleg-designer commented
@IgorekLoschinin  When i try to start game they crush with this text in console "Segmentation fault (core dumped)" need to fix this.

2021-07-07 07:13 UTC, EndrII commented
please import last changes from main into this branch (using merge strategy)

2021-07-08 18:20 UTC, EndrII approved these changes
Will be merget

2021-07-08 18:20 UTC, merged