Added load objects.
QuasarApp/Crawl pull request #91
Opened 2021-07-22 19:03 UTC by IgorekLoschinin

fix #79 Added upload objects.

2021-07-22 19:15 UTC, EndrII commented
please update QuasarAppLib to last main commit for fix build

2021-07-24 14:50 UTC, EndrII requested changes

2021-07-24 14:50 UTC, EndrII commented on src/CrawlAbstractLvl/private/abslvlworld.cpp
> +
i think you forget about light object

2021-07-24 14:50 UTC, EndrII commented on src/CrawlAbstractLvl/private/abslvlworld.cpp
> +    return "qrc:/hdr/hdr/testHDR.hdr";
please restore old hdr map

2021-07-24 15:18 UTC, EndrII requested changes

2021-07-24 15:18 UTC, EndrII commented on src/CrawlAbstractLvl/private/obstaclered.cpp
> +    setSize({2,2,2});
```suggestion
    setSize({1,1,1});
```
please use the the 1 as a scale factor. if you think that object is small then please create new task for the @Oleg-designer

2021-07-24 15:18 UTC, EndrII commented on src/CrawlAbstractLvl/private/obstaclered.cpp
> +    setposition({300, 0, 200});
```suggestion

```
The position of object automatically recalculate in world initialization

2021-07-24 16:28 UTC, EndrII commented on src/Client/languages/tr.ts
> +    <name>AbstractLvl::AbsLvlWorld</name>
maybe you added wrong name for level

2021-07-24 17:11 UTC, IgorekLoschinin commented on src/Client/languages/tr.ts
> +    <name>AbstractLvl::AbsLvlWorld</name>
I changed the name of the class. I FIX.

2021-07-24 18:01 UTC, EndrII approved these changes

2021-07-24 18:05 UTC, merged